openapi: 3.0.0
info:
  title: Test App
  description: GraphQL API for unit tests  
  version: 1.0.0
paths:
  /api/v1/test-operation:
    post:
      operationId: testOperation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TestParams"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TestResponse"
components:
  schemas:
    TestParams:
      type: object
      required:
        - query
      properties:
        query:
          type: string
        parameters:
          type: object
    TestResponse:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        answer:
          type: string